name: test

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v4.0.0

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with lint

      - name: Lint code
        run: |
          poetry run isort --check .
          poetry run black --check .
          poetry run flake8 .
