name: test-publish

on:
  push:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3.3.0

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.2.2"

      - name: Publish
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"

          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry build
          #poetry publish --build --username __token__ --password ${{ secrets.PYPI_TEST_TOKEN }} --repository testpypi
